set t_Co=256
colorscheme torte
set cursorline
hi CursorLine cterm=none ctermbg=DarkMagenta ctermfg=White
set cursorcolumn
syntax enable
set nocompatible
set number
set smartcase
set hlsearch
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set confirm
set backspace=indent,eol,start
set history=500
set laststatus=2
